### ISSUE TITLE
request to please drop "TBD" category in local vs. intl. partners visual

### ISSUE THREAD

**Issue by cnichols3h** [USAID-OHA-SI/pedal_to_the_metal#37]
I am channeling a request from Erin Dunlap that came up in our Sprint 1 meeting today.  Erin QC'ed all of the budget and HRH values on the HIV Data Briefers.  All # s check out just fine.  She is requesting to please remove the "TBD" category in the local / intl. partner breakdown.  This is b/c it causes some values to go above 100% and it is different from how this visual is set up in Pano., which displays local and intl., but has the TBDs removed.  If you are able to please make this fix and remove the TBDs for that visual, that will be the last requested change to these sections.  If you have any follow up questions, Erin can answer.  Thx!

**Comment by achafetz** [comment]
TBD mechanism are defined as those that have the mech name and/or prime partner name as TBD:

`ifelse(mech_name == "TBD" | prime_partner_name == "TBD", "TBD", local_prime_partner)`
