### ISSUE TITLE
DHI Tables validating with Pano

### ISSUE THREAD

**Issue by erdunlap** [USAID-OHA-SI/pedal_to_the_metal#43]
Unsure if anyone else is validating this table, I QC'd Pano with the 1:40pm briefers in the folder and Haiti, Zim, and Zam have some minor discrepancies. Uganda seems very off, by $, Sys, and Act, for both USAID and OU levels. Recommend an additional person QCs this table, especially Uganda, in case I'm missing something.

**Comment by achafetz** [comment]
Issue stems from including products where more than just "confiirmed" as their status.

Fix - include a filter for this:  `dhi_approval_workflow_status == "Confirmed"`
